# Assignment - **1**

In [ ]:
#Task 1:Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [ ]:
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4']) #F=feautures
first_obs = df.iloc[0]# To access individual observations
print(df)
print("First observation:")
print(first_obs)

         F1        F2        F3        F4
0  1.110293  0.202626 -0.042782 -1.465921
1 -1.015765  0.362152  0.686825  0.071445
2 -1.189778  2.528367  1.057487  0.135847
3  0.849125 -0.831997 -0.818775  0.096233
First observation:
F1    1.110293
F2    0.202626
F3   -0.042782
F4   -1.465921
Name: 0, dtype: float64

In [ ]:
# Task 2:Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4']) #F=feautures
df=df.rename(columns={'F1':'Random value 1','F2':'Random value 2','F3':'Random value 3','F4':'Random value 4'})
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0       -1.591513       -0.841962        0.607988       -0.475016
1       -0.656917       -0.088063        1.027402        1.434701
2       -0.324460        1.072213       -1.620793        0.228842
3       -0.417990        1.934676        1.279561       -0.784562

In [ ]:
# Task 3:Find the descriptive statistics of the 'df' dataframe

In [ ]:
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4'])
statistics = df.describe()
print(statistics)

             F1        F2        F3        F4
count  4.000000  4.000000  4.000000  4.000000
mean  -1.054014  0.276787 -0.021367  0.150333
std    1.872622  0.461254  0.596878  0.798984
min   -3.136188 -0.365005 -0.470367 -0.720002
25%   -2.362107  0.123513 -0.361601 -0.414316
50%   -0.944559  0.382156 -0.232928  0.169358
75%    0.363534  0.535430  0.107306  0.734006
max    0.809249  0.707842  0.850753  0.982618

In [ ]:
# Task 4:Check for the null values in 'df' and find the data type of the columns.

In [ ]:
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4'])
null_values = df.isnull().any()
print("Nullvalues")
print(null_values)
type_of_the_data = df.dtypes
print("Datatype:")
print(type_of_the_data)

Nullvalues
F1    False
F2    False
F3    False
F4    False
dtype: bool
Datatype:
F1    float64
F2    float64
F3    float64
F4    float64
dtype: object

In [ ]:
#to get null values 
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
random_values[1,2] = None
random_values[3,0] = None
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4'])
print(df)
null_values = df.isnull().any()
print("Nullvalues")
print(null_values)
type_of_the_data = df.dtypes
print("Datatype:")
print(type_of_the_data)

         F1        F2        F3        F4
0 -0.344983  0.194403  0.134044  0.291712
1 -0.782811 -1.323078       NaN  0.031824
2  0.021625  0.485428  1.672387 -0.316169
3       NaN -1.217970  0.810471 -1.005008
Nullvalues
F1     True
F2    False
F3     True
F4    False
dtype: bool
Datatype:
F1    float64
F2    float64
F3    float64
F4    float64
dtype: object

In [ ]:
#Task 5:Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [ ]:
import pandas as pd
import numpy as np
random_values = np.random.randn(4,4)
df = pd.DataFrame(random_values , columns=['F1','F2','F3','F4']) #F=feautures
df=df.rename(columns={'F1':'Random value 1','F2':'Random value 2','F3':'Random value 3','F4':'Random value 4'})
loc_col = df.loc[:,['Random value 2','Random value 3']]#using loc method
print("Loc method:")
print(loc_col)
index_col = df.iloc[:,[1,2]]#using index location method
print("Index method:")
print(index_col)

Loc method:
   Random value 2  Random value 3
0        0.453834       -0.780335
1       -1.444298       -0.772597
2        0.384774       -1.815736
3        0.231933       -1.254180
Index method:
   Random value 2  Random value 3
0        0.453834       -0.780335
1       -1.444298       -0.772597
2        0.384774       -1.815736
3        0.231933       -1.254180